[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
#  color scheme
# ==========================================================
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  source ~/.config/nvim/plugins/molokai.rc.vim
'''

# ==========================================================
#  editor config
# ==========================================================
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# ==========================================================
#  Auto Complete
# ==========================================================
[[plugins]]
repo = 'cohama/lexima.vim'

# ==========================================================
#  terminal
# ==========================================================
[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/neoterm.rc.vim
'''

# ==========================================================
#  powerline
# ==========================================================
[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
source ~/.config/nvim/plugins/airline.rc.vim
'''

# フォントは以下からダウンロードする
# https://github.com/powerline/fonts
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
let g:airline_theme='molokai'
'''

[[plugins]]
repo = 'gcmt/taboo.vim'
depends = 'vim-airline'
hook_add = '''
if !has('nvim')
  set guioptions-=e
  set sessionoptions+=tabpages,globals
endif
let g:taboo_tab_format=' t%N %f%m '
let g:taboo_tabline = 0
'''
