# ==========================================================
#  Syntax Highlight
# ==========================================================
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx', 'typescriptreact']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'GutenYe/json5.vim'
on_ft = ['json5']

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ['elixir']

# ==========================================================
#  Auto Complete
# ==========================================================
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.rc.vim
  call deoplete#enable()
'''
